services:
  - docker 
script:
  - docker image build -t dockerdaisystoner/travis .
deploy: 
  provider: script 
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push dockerdaisystonr/travis 
